import type { Metadata } from "next";
import "./globals.css";
import { lato, geistSans } from "@/app/ui/fonts";
import Nav from "@/components/nav/Nav";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} ${geistSans.className} antialiased min-h-screen`}
      >
        <div className="min-h-screen flex flex-col items-stretch justify-between">
          <Nav />
          <div className="p-3">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
